// animelist/duck/types.js
// ...
const REQUEST_CURRENT_ANIME_SEASON = "REQUEST_CURRENT_ANIME_SEASON";
const REQUEST_FILTERED_SEASON = "REQUEST_FILTERED_SEASON";

export default {
  REQUEST_CURRENT_ANIME_SEASON,
  REQUEST_FILTERED_SEASON
};
